name: WebInterface
main: org.micoli.minecraft.webInterface.WebInterface
version: 0.2
description: Heroes, Items and recipes interface 
depend: [Vault,morgUtils,Heroes]
commands:
    webinterface:
      description: main command 