name: WebInterface
main: org.micoli.minecraft.webInterface.WebInterface
version: 0.1
description: Heroes, Items and recipes interface 
depend: [Vault,morgUtils,Heroes]
commands:
    heroesint:
      description: main command 